export const firebaseConfig = {
  apiKey: "AIzaSyCQHrtgTZr5sZVElyfy2TBcENC0cwzmkhg",
  authDomain: "safety001-5091e.firebaseapp.com",
  databaseURL: "https://safety001-5091e-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "safety001-5091e",
  storageBucket: "safety001-5091e.firebasestorage.app",
  messagingSenderId: "753126039012",
  appId: "1:753126039012:web:68ec71700a164db531fbf1",
  measurementId: "G-DXS3VQE8R3"
};

export const CONFIGURED = !firebaseConfig.apiKey.startsWith("YOUR");
export const ADMIN_PW   = "safety2025";
export const GAS_URL    = "https://script.google.com/macros/s/AKfycbyS-dsOL7tjKLcrDrXV-iDZurGxAhzgpT0GOWF4QWEYpWyFygqMZjIsKcpQL0zuESMn/exec";
export const APP_NAME   = "광명사업부 안전관리 시스템";

// 마스터 관리자 시드 — 코드에 고정되어 항상 마스터 권한 (회수 불가, 권한의 뿌리)
export const MASTER_EMAILS = [
  "chepp07@gmail.com"
];

// 레거시 관리자 — 첫 로그인 시 DB role=admin 으로 자동 이관됨 (이후엔 마스터가 화면에서 관리)
export const ADMIN_EMAILS = [
  "dlacksgus@gmail.com",
  "rlarufo123456@gmail.com",
  "look830724@gmail.com",
  "ab734741@gmail.com",
  "chepp07@gmail.com"
];

export const SITES = [
  "광명1범퍼사업소","광명2범퍼사업소","광명1서열사업소",
  "광명2서열사업소","광명JIT사업소","광명장비사업소","기타"
];

export const IMGBB_KEY = "f6ceb324bed80f18fbfcf46a5fca6450";

export const T = {
  ko: {
    langBtn:        "🇨🇳 中文",
    formTitle:      "현장 사고 접수",
    formDesc:       "사고 발생 즉시 접수해 주세요.\nLevel 1·2는 전화 보고를 병행해 주세요.",
    secSite:        "📍 사업소",
    site:           "사업소",
    secReporter:    "👤 접수자 정보",
    reporter:       "접수자 성명",
    rank:           "직급",
    phone:          "연락처",
    secDateTime:    "🕐 사고 발생 일시",
    dateTimeAuto:   "현재 시각 자동 입력 — 필요 시 수정",
    location:       "사고 발생 위치",
    secClass:       "🗂️ 사고 분류",
    complex:        "복합사고",
    complexDesc:    "2가지 이상의 사고 유형이 동시에 발생한 경우 체크",
    accType:        "사고 유형",
    complexHint:    "복합사고 — 중복선택 가능",
    accDetail:      "세부 유형",
    secUrgency:     "🚨 긴급도",
    secLineStop:    "⚡ 라인중단 여부",
    secCustEffect:  "🏭 고객사 영향",
    yesNo:          ["예","아니오"],
    secPerson:      "🧑‍⚕️ 인사사고 대상자",
    alone:          "단독사고",
    both:           "쌍방사고",
    victim:         "피해자",
    perp:           "가해자",
    addPerson:      "+ 추가",
    unknown:        "미확인",
    affiliation:    "소속",
    secAction:      "📝 현황 및 조치",
    voiceBtn:       "🎤 음성으로 빠른 입력",
    voiceOn:        "음성 입력 중... (탭하여 중지)",
    voiceGuideTitle:"🎤 지금 말씀해 주세요!",
    voiceGuideItems:[
      {label:"발생 위치",    ex:"1공장 도킹존"},
      {label:"무슨 일이 있었는지", ex:"부품 낙하로 작업자 손 부상"},
      {label:"현재 상태",    ex:"라인 중단, 119 신고 완료"},
      {label:"추가 필요사항",ex:"안전팀 출동 요청"},
    ],
    voiceExample:   "전체 예시",
    voiceExText:    "\"1공장 도킹존, 부품 낙하로 작업자 손 부상, 라인 중단, 119 신고 완료\"",
    situation:      "현재 상황",
    situationPh:    "사고 발생 경위 및 현재 상황을 간략히 기술해 주세요.",
    action:         "즉시 조치 내용",
    actionPh:       "취한 즉시 조치를 입력해 주세요. (없으면 '없음' 입력)",
    support:        "추가 지원 필요 여부",
    supportPh:      "예: 안전팀 현장 출동 요청 (없으면 '없음' 입력)",
    secPhoto:       "📷 현장 사진 첨부",
    photoDesc:      "최대 3장까지 첨부 가능 · JPG, PNG, GIF 지원",
    photoSelect:    "사진 선택",
    photoMax:       "최대 3장 첨부 완료",
    photoUploading: "업로드중...",
    secCheck:       "✅ 확인 사항",
    checks: [
      "현장을 통제하거나 2차 사고를 예방하기 위한 즉시 조치를 취했습니다.",
      "사진 촬영 등 현장 기록을 완료하였습니다.",
      "허위 보고 시 규정에 따라 처리될 수 있음을 확인했습니다."
    ],
    submitBtn:      "사고 접수하기",
    submitting:     "접수 중...",
    goMain:         "← 메인",
    goLogin:        "← 로그인",
    myReport:       "📋 내 접수 조회",
    adminPage:      "관리자 페이지",
    successTitle:   "사고 접수가 완료되었습니다.",
    successDesc:    "담당자에게 즉시 통보됩니다.\nLevel 1·2 사고는 전화로 추가 보고를 병행해 주세요.",
    newAccident:    "새 사고 접수",
    voiceLang:      "ko-KR",
    ranks: ["사원","조장","반장","주임","대리","과장","차장","부장","부소장","소장","상무","기타"],
    lineStops: [
      {val:"라인중단발생", color:"#b71c1c", bg:"#fff5f5", border:"#f5c6c6", desc:"현재 라인이 중단된 상태"},
      {val:"라인중단예상", color:"#e65100", bg:"#fff8f0", border:"#fcd8a8", desc:"중단 가능성이 높은 상태"},
      {val:"미장착",       color:"#7b5e00", bg:"#fffde7", border:"#ffe082", desc:"부품 미장착으로 생산 차질"},
      {val:"라인영향없음", color:"#2e7d32", bg:"#f0faf0", border:"#b8e0ba", desc:"라인 정상 운영 중"},
    ],
    levels: [
      {val:"1", label:"Level 1", sub:"최긴급", bg:"#fff5f5", color:"#b71c1c", border:"#f5c6c6"},
      {val:"2", label:"Level 2", sub:"긴급",   bg:"#fff8f0", color:"#e65100", border:"#fcd8a8"},
      {val:"3", label:"Level 3", sub:"일반",   bg:"#f0faf0", color:"#2e7d32", border:"#b8e0ba"},
    ],
    accTypes: ["인사사고","제품사고","공급사고","차량사고"],
    accDetailMap: {
      "인사사고": [
        {val:"중대재해",   desc:"사망·3일 이상 휴업이 필요한 부상 또는 질병"},
        {val:"일반재해",   desc:"병원 치료가 필요한 부상 (1~2일 휴업 포함)"},
        {val:"경미사고",   desc:"응급처치 수준의 가벼운 부상 (휴업 없음)"},
        {val:"아차사고",   desc:"다칠 뻔했으나 실제 부상은 없었던 위험 상황"},
      ],
      "제품사고": [
        {val:"파손·충격",  desc:"낙하·충돌·압력 등으로 인한 제품 파손 또는 변형"},
        {val:"오염·이물",  desc:"이물질 혼입, 먼지·유분 등 오염으로 품질 불량"},
        {val:"포장불량",   desc:"포장재 파손, 라벨 오류, 포장 규격 미준수"},
        {val:"운송중 손상",desc:"운반·상하차·보관 중 발생한 제품 손상"},
      ],
      "공급사고": [
        {val:"이종·혼입",  desc:"다른 품번·사양의 부품이 섞여 납입된 경우"},
        {val:"불량품 납입",desc:"품질 기준 미달 부품이 공급된 경우"},
        {val:"결품·수량오류",desc:"납입 수량 부족, 누락, 수량 불일치"},
        {val:"서열오류",   desc:"서열·순서가 생산 계획과 다르게 납입된 경우"},
        {val:"납입지연",   desc:"약정 시간보다 늦게 납입되어 라인에 영향"},
        {val:"라인투입오류",desc:"잘못된 라인·공정에 부품이 투입된 경우"},
      ],
      "차량사고": [
        {val:"자차사고",   desc:"당사 차량 단독 사고 (접촉·전복·충돌 등)"},
        {val:"대물사고",   desc:"타인 차량·시설물·재산에 피해를 입힌 사고"},
      ],
    },
  },
  zh: {
    langBtn:        "🇰🇷 한국어",
    formTitle:      "现场事故报告",
    formDesc:       "发生事故后请立即填写。\nLevel 1·2 请同时进行电话报告。",
    secSite:        "📍 事业所",
    site:           "事业所",
    secReporter:    "👤 报告人信息",
    reporter:       "报告人姓名",
    rank:           "职级",
    phone:          "联系电话",
    secDateTime:    "🕐 事故发生时间",
    dateTimeAuto:   "自动填入当前时间 — 如需修改请编辑",
    location:       "事故发生地点",
    secClass:       "🗂️ 事故分类",
    complex:        "复合事故",
    complexDesc:    "同时发生两种以上事故类型时勾选",
    accType:        "事故类型",
    complexHint:    "复合事故 — 可多选",
    accDetail:      "细分类型",
    secUrgency:     "🚨 紧急程度",
    secLineStop:    "⚡ 停线情况",
    secCustEffect:  "🏭 客户影响",
    yesNo:          ["是","否"],
    secPerson:      "🧑‍⚕️ 人员事故对象",
    alone:          "单方事故",
    both:           "双方事故",
    victim:         "受害者",
    perp:           "肇事者",
    addPerson:      "+ 添加",
    unknown:        "不明",
    affiliation:    "所属",
    secAction:      "📝 现状及处置",
    voiceBtn:       "🎤 语音快速输入",
    voiceOn:        "语音输入中... (点击停止)",
    voiceGuideTitle:"🎤 请您说话！",
    voiceGuideItems:[
      {label:"发生地点",  ex:"1工厂对接区"},
      {label:"发生了什么",ex:"零件跌落导致工人手部受伤"},
      {label:"当前状态",  ex:"停线，已呼叫119"},
      {label:"需要协助",  ex:"请求安全团队到场"},
    ],
    voiceExample:   "示例",
    voiceExText:    "\"1工厂对接区，零件跌落导致工人手部受伤，停线，已呼叫119\"",
    situation:      "当前状况",
    situationPh:    "请简要描述事故经过和当前状况。",
    action:         "即时处置内容",
    actionPh:       "请填写已采取的即时措施。(无则填写'无')",
    support:        "是否需要额外支援",
    supportPh:      "例：请求安全团队到场 (无则填写'无')",
    secPhoto:       "📷 现场照片",
    photoDesc:      "最多可附3张 · 支持JPG, PNG, GIF",
    photoSelect:    "选择照片",
    photoMax:       "已附3张（最大）",
    photoUploading: "上传中...",
    secCheck:       "✅ 确认事项",
    checks: [
      "已采取措施控制现场或防止二次事故。",
      "已完成拍照等现场记录工作。",
      "确认虚假报告将依规处理。"
    ],
    submitBtn:      "提交事故报告",
    submitting:     "提交中...",
    goMain:         "← 主页",
    goLogin:        "← 登录",
    myReport:       "📋 我的报告查询",
    adminPage:      "管理员页面",
    successTitle:   "事故报告已提交完成。",
    successDesc:    "负责人将立即收到通知。\nLevel 1·2 请同时进行电话报告。",
    newAccident:    "新增事故报告",
    voiceLang:      "zh-CN",
    ranks: ["员工","组长","班长","主任","代理","科长","次长","部长","副所长","所长","常务","其他"],
    lineStops: [
      {val:"라인중단발생", color:"#b71c1c", bg:"#fff5f5", border:"#f5c6c6", desc:"当前生产线已停止"},
      {val:"라인중단예상", color:"#e65100", bg:"#fff8f0", border:"#fcd8a8", desc:"停线可能性较高"},
      {val:"미장착",       color:"#7b5e00", bg:"#fffde7", border:"#ffe082", desc:"零件未装配导致生产受阻"},
      {val:"라인영향없음", color:"#2e7d32", bg:"#f0faf0", border:"#b8e0ba", desc:"生产线正常运行"},
    ],
    levels: [
      {val:"1", label:"Level 1", sub:"最紧急", bg:"#fff5f5", color:"#b71c1c", border:"#f5c6c6"},
      {val:"2", label:"Level 2", sub:"紧急",   bg:"#fff8f0", color:"#e65100", border:"#fcd8a8"},
      {val:"3", label:"Level 3", sub:"一般",   bg:"#f0faf0", color:"#2e7d32", border:"#b8e0ba"},
    ],
    accTypes: ["人员事故","产品事故","供应事故","车辆事故"],
    accDetailMap: {
      "人员事故": [
        {val:"重大灾害",   desc:"死亡或需休假3天以上的伤害或疾病"},
        {val:"一般灾害",   desc:"需就医的伤害（含1~2天休假）"},
        {val:"轻微事故",   desc:"仅需急救处理的轻伤（无需休假）"},
        {val:"险情事故",   desc:"险些受伤但实际未造成伤害的危险情况"},
      ],
      "产品事故": [
        {val:"破损·冲击",  desc:"因跌落·碰撞·压力等造成的产品破损或变形"},
        {val:"污染·异物",  desc:"异物混入、灰尘油污等污染导致品质不良"},
        {val:"包装不良",   desc:"包装材料破损、标签错误、包装规格不符"},
        {val:"运输中损坏",  desc:"搬运·装卸·保管过程中产生的产品损坏"},
      ],
      "供应事故": [
        {val:"异种·混入",  desc:"不同品番·规格的零件混入供应"},
        {val:"不良品供应",  desc:"不符合品质标准的零件被供应"},
        {val:"缺件·数量错误",desc:"供应数量不足、漏发、数量不一致"},
        {val:"序列错误",   desc:"零件序列·顺序与生产计划不符"},
        {val:"供应延迟",   desc:"晚于约定时间供应，影响生产线"},
        {val:"投入错误",   desc:"零件投入了错误的生产线·工序"},
      ],
      "车辆事故": [
        {val:"自车事故",   desc:"本公司车辆单方事故（接触·翻覆·碰撞等）"},
        {val:"对物事故",   desc:"对他人车辆·设施·财产造成损害的事故"},
      ],
    },
    accTypeMap: {"人员事故":"인사사고","产品事故":"제품사고","供应事故":"공급사고","车辆事故":"차량사고"},
    accDetailKo: {
      "重大灾害":"중대재해","一般灾害":"일반재해","轻微事故":"경미사고","险情事故":"아차사고",
      "破损·冲击":"파손·충격","污染·异物":"오염·이물","包装不良":"포장불량","运输中损坏":"운송중 손상",
      "异种·混入":"이종·혼입","不良品供应":"불량품 납입","缺件·数量错误":"결품·수량오류",
      "序列错误":"서열오류","供应延迟":"납입지연","投入错误":"라인투입오류",
      "自车事故":"자차사고","对物事故":"대물사고",
    },
  },
};
